### PR TITLE
Run embedded migrations

### LINKED ISSUE #52: [BUG] Database Not Initialized on App Launch
### Describe the bug
The database crashes when running for the first time in a non-dev environment

#### To Reproduce
Tested on dev/add-default-user
- Delete the local.db file within the coms-console folder within the app data dir
- Try running the build version
#### Expected behavior
- Initializes the local.db
### Screenshots
N/A
Desktop
    OS: MacOS

### Additional context
N/A

### PR DESCRIPTION
**Pull request by Matgenius04**
### Changes
- [x] Added a db_setup function that embeds the tables in the schema and runs pending migrations.

### How to Test
 - [x] Navigate to the coms-console folder within the [Local Data Dir](https://v1.tauri.app/v1/api/js/path/#localdatadir) and delete local.db if it exists
 - [x] Run `tauri build`
 - [x] Run the packaged application and see if it generates a new local.db

### Testing Considerations
- N/A

Closes #52

### CODE REVIEW

File: src-tauri/src/main.rs [hunk 1]
```diff
@@ -31,6 +32,7 @@ fn main() {
                     .into_os_string()
                     .into_string()
                     .unwrap();
+                setup_db(db_path.as_str());
```
Comment (Saoski) [inline src-tauri/src/main.rs:35]: Looks good! Now we shouldn't have to run the database reset if we change to schema

**Review by Saoski — APPROVED** [review]
🔥
